cars_data = [
  {
    make: "Porsche",
    model: "911 GT3",
    hp: 510,
    nm: 470,
    engine: "4.0L flat-six",
    gearbox: "automatic",
    fuel: "benzine",
    rpm_redline: 9000,
    accTo100: 3.4,
    topSpeed: 319,
    drive: "rear wheels",
    priceEur: 1000,
    imgPath: "img/cars/porsche-911/main",
  },
  {
    make: "Lamborghini",
    model: "Huracan Performante",
    hp: 640,
    nm: 600,
    engine: "5.2L N/A V10",
    gearbox: "automatic",
    fuel: "benzine",
    rpm_redline: 8500,
    accTo100: 2.9,
    topSpeed: 325,
    drive: "4x4 (permanent)",
    priceEur: 900,
    imgPath: "img/cars/lamborghini-perf/main",
  },
  {
    make: "McLaren",
    model: "Artura",
    hp: 680,
    nm: 720,
    engine: "3.0L TT V6",
    gearbox: "automatic",
    fuel: "benzine",
    rpm_redline: 8500,
    accTo100: 3.0,
    topSpeed: 328,
    drive: "rear wheels",
    priceEur: 1100,
    imgPath: "img/cars/mclaren-artura/main",
  },
];
